version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7-browsers
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dependency-cache-{{ .Branch }}-{{ .Revision }}
            - dependency-cache-develop
            - dependency-cache-master
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: |
            mkdir -p ./reports
            npm run lint -- --format=junit --output-file ./reports/eslint.xml
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
